//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpFile.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpFile.Infrastructure.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Settings&gt;
        ///  &lt;ParentType&gt;Dual&lt;/ParentType&gt;
        ///  &lt;Width&gt;500&lt;/Width&gt;
        ///  &lt;Height&gt;500&lt;/Height&gt;
        ///  &lt;SplitterPercentage&gt;50&lt;/SplitterPercentage&gt;
        ///  &lt;DirectoriesSortedFirst&gt;true&lt;/DirectoriesSortedFirst&gt;
        ///  &lt;Icons&gt;
        ///    &lt;ShowOverlay&gt;true&lt;/ShowOverlay&gt;
        ///    &lt;Extensions&gt;
        ///      &lt;Extension&gt;.exe&lt;/Extension&gt;
        ///      &lt;Extension&gt;.lnk&lt;/Extension&gt;
        ///      &lt;Extension&gt;.dll&lt;/Extension&gt;
        ///      &lt;Extension&gt;.ps&lt;/Extension&gt;
        ///      &lt;Extension&gt;.scr&lt;/Extension&gt;
        ///      &lt;Extension&gt;.ico&lt;/Extension&gt;
        ///      &lt;Extension&gt;.icn&lt;/Extension&gt;
        ///    &lt;/E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ilmerge_settings {
            get {
                return ResourceManager.GetString("ilmerge_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Settings&gt;
        ///  &lt;ParentType&gt;Dual&lt;/ParentType&gt;
        ///  &lt;Width&gt;500&lt;/Width&gt;
        ///  &lt;Height&gt;500&lt;/Height&gt;
        ///  &lt;SplitterPercentage&gt;50&lt;/SplitterPercentage&gt;
        ///  &lt;DirectoriesSortedFirst&gt;true&lt;/DirectoriesSortedFirst&gt;
        ///  &lt;Icons&gt;
        ///    &lt;ShowOverlay&gt;true&lt;/ShowOverlay&gt;
        ///    &lt;Extensions&gt;
        ///      &lt;Extension&gt;.exe&lt;/Extension&gt;
        ///      &lt;Extension&gt;.lnk&lt;/Extension&gt;
        ///      &lt;Extension&gt;.dll&lt;/Extension&gt;
        ///      &lt;Extension&gt;.ps&lt;/Extension&gt;
        ///      &lt;Extension&gt;.scr&lt;/Extension&gt;
        ///      &lt;Extension&gt;.ico&lt;/Extension&gt;
        ///      &lt;Extension&gt;.icn&lt;/Extension&gt;
        ///    &lt;/E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
    }
}
